server:
  port: 9090
spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Sellers
          jwk-set-uri: http://localhost:8080/realms/Sellers/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: service1
          uri: https://www.google.co.in
          predicates:
            - Path=/service1/**
          filters:
            - StripPrefix=1
        - id: service2
          uri: https://www.facebook.com
          predicates:
            - Path=/service2/**
          filters:
            - StripPrefix=1
            
